name: Greeting from Mona

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
     - name: Post to a Slack channel
         id:slack
       uses: slackapi/slack-github-action@v1.23.0
       with:
        channel-id: 'CHANNEL_ID,ANOTHER_CHANNEL_ID'
        slack-message: |-
                         GitHub build result: ${{ job.status }}${{ github.event.pull_request.html_url || github.event.head_commit.url }}
        env:
             SLACK_BOT_TOKEN: '${{ secrets.SLACK_BOT_TOKEN }}'

