name: Release notifications

on: 
 release: 
   types: [published]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
     - name: Post to a Slack channel
         id:slack
       uses: slackapi/slack-github-action@v1.23.0
       with:
        channel-id: 'test1,test2'
        slack-message: " ${{github.ref_name}} is released on this link"
                         
       env:
             SLACK_BOT_TOKEN: '${{ secrets.SLACK_BOT_TOKEN }}'

