name: releases announcement
on: 
release:
types: [created]
jobs:  send_message:
name: Send Release Announcement
runs-on: ubuntu-latest
steps:
- name: Send Message
id: send_message
run: |
MESSAGE=":newspaper:Thanks to everyone\'s hard work, ${{github.ref_name}} is now released to all users:exclamation:"
curl -X POST -H 'Content-type:application/json' --data "{'text':'$MESSAGE'}" "https://hooks.slack.com/services/{${{secrets.RELEASE_TEST1_WEBHOOKIDENTIFIER}},${{secrets.RELEASE_TEST2_WEBHOOKIDENTIFIER}}}"
